import type { Metadata } from "next";
import { inter } from "./fonts";

import "./globals.css";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "lifridraws",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <header>
          <Header />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
